server:
  port: 8083
springdoc:
  swagger-ui:
    url: /user-auth-service-api.yaml
    path: /swagger-ui.html
spring:
  application:
    name: userauth
  datasource:
    url: jdbc:mysql://localhost:3306/userauth_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
