#server.port=8081
#spring.jackson.date-format=org.openapitools.RFC3339DateFormat
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
server:
  port: 8081  # or 8082, 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permissiondb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
