openapi: 3.0.1
info:
  description: "API to manage permissions (create, retrieve, delete, and fetch by\
    \ ID)."
  title: Permission Management API
  version: 1.0.0
servers:
- url: http://localhost:8081
paths:
  /api/permissions:
    get:
      operationId: getAllPermissions
      responses:
        "200":
          content:
            application/json:
              example:
              - id: 1
                name: VIEW_REPORTS
                description: Grants access to view reports
              - id: 2
                name: EDIT_USERS
                description: Allows editing user information
              schema:
                items:
                  $ref: '#/components/schemas/PermissionResponse'
                type: array
          description: List of all permissions
      summary: Retrieve all permissions
      x-accepts:
      - application/json
    post:
      operationId: createPermission
      requestBody:
        content:
          application/json:
            example:
              name: VIEW_REPORTS
              description: Grants access to view reports
            schema:
              $ref: '#/components/schemas/PermissionRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              example:
                id: 1
                name: VIEW_REPORTS
                description: Grants access to view reports
              schema:
                $ref: '#/components/schemas/PermissionResponse'
          description: Permission created successfully
        "400":
          description: Invalid input
      summary: Create a new permission
      x-content-type: application/json
      x-accepts:
      - application/json
  /api/permissions/{id}:
    delete:
      operationId: deletePermissionById
      parameters:
      - description: ID of the permission to delete
        explode: false
        in: path
        name: id
        required: true
        schema:
          example: 1
          type: integer
        style: simple
      responses:
        "204":
          description: Permission deleted successfully
        "404":
          description: Permission not found
      summary: Delete permission by ID
      x-accepts:
      - application/json
    get:
      operationId: getPermissionById
      parameters:
      - description: ID of the permission
        explode: false
        in: path
        name: id
        required: true
        schema:
          example: 1
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                id: 1
                name: VIEW_REPORTS
                description: Grants access to view reports
              schema:
                $ref: '#/components/schemas/PermissionResponse'
          description: Permission found
        "404":
          description: Permission not found
      summary: Get permission by ID
      x-accepts:
      - application/json
components:
  schemas:
    PermissionRequest:
      example:
        name: VIEW_REPORTS
        description: Grants access to view reports
      properties:
        name:
          example: VIEW_REPORTS
          maxLength: 15
          type: string
        description:
          example: Grants access to view reports
          maxLength: 255
          type: string
      required:
      - description
      - name
      type: object
    PermissionResponse:
      example:
        name: VIEW_REPORTS
        description: Grants access to view reports
        id: 1
      properties:
        id:
          example: 1
          type: integer
        name:
          example: VIEW_REPORTS
          type: string
        description:
          example: Grants access to view reports
          type: string
      type: object
