/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.13.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.RolePermissionRequest;
import org.openapitools.model.RolePermissionResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-06-11T09:32:45.327152400+05:30[Asia/Calcutta]", comments = "Generator version: 7.13.0")
@Validated
@Tag(name = "api", description = "the api API")
public interface ApiApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /api/role-permissions : List all role-permission mappings
     *
     * @return List of mappings (status code 200)
     */
    @Operation(
        operationId = "apiRolePermissionsGet",
        summary = "List all role-permission mappings",
        responses = {
            @ApiResponse(responseCode = "200", description = "List of mappings", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = RolePermissionResponse.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/role-permissions",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<RolePermissionResponse>> apiRolePermissionsGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"permissions\" : [ \"CREATE\", \"READ\", \"UPDATE\" ], \"roleName\" : \"ADMIN\", \"id\" : 1 }, { \"permissions\" : [ \"CREATE\", \"READ\", \"UPDATE\" ], \"roleName\" : \"ADMIN\", \"id\" : 1 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /api/role-permissions : Add new role-permission mapping
     *
     * @param rolePermissionRequest  (required)
     * @return Mapping created (status code 201)
     */
    @Operation(
        operationId = "apiRolePermissionsPost",
        summary = "Add new role-permission mapping",
        responses = {
            @ApiResponse(responseCode = "201", description = "Mapping created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RolePermissionResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/role-permissions",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<RolePermissionResponse> apiRolePermissionsPost(
        @Parameter(name = "RolePermissionRequest", description = "", required = true) @Valid @RequestBody RolePermissionRequest rolePermissionRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"permissions\" : [ \"CREATE\", \"READ\", \"UPDATE\" ], \"roleName\" : \"ADMIN\", \"id\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /api/role-permissions/{id} : Delete role-permission mapping by ID
     *
     * @param id  (required)
     * @return Deleted successfully (status code 204)
     *         or Mapping not found (status code 404)
     */
    @Operation(
        operationId = "deleteRolePermissionById",
        summary = "Delete role-permission mapping by ID",
        responses = {
            @ApiResponse(responseCode = "204", description = "Deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Mapping not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/role-permissions/{id}"
    )
    
    default ResponseEntity<Void> deleteRolePermissionById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/role-permissions/{id} : Get role-permission mapping by ID
     *
     * @param id  (required)
     * @return Mapping found (status code 200)
     *         or Mapping not found (status code 404)
     */
    @Operation(
        operationId = "getRolePermissionById",
        summary = "Get role-permission mapping by ID",
        responses = {
            @ApiResponse(responseCode = "200", description = "Mapping found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = RolePermissionResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Mapping not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/role-permissions/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<RolePermissionResponse> getRolePermissionById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Integer id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"permissions\" : [ \"CREATE\", \"READ\", \"UPDATE\" ], \"roleName\" : \"ADMIN\", \"id\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
